# Used to test out the theme
project:
  type: seedcase-theme

website:
  title: "Seedcase Quarto theme"
  site-url: "https://seedcase-project.github.io/seedcase-theme/"
  repo-url: "https://github.com/seedcase-project/seedcase-theme"
  navbar:
    logo: _extensions/seedcase-theme/logos/seedcase/icon.svg
    logo-alt: "Seedcase logo"
    left:
      - text: "Welcome"
        href: index.qmd
      - text: "Menu"
        menu:
          - href: index.qmd
            text: "Home"
  sidebar:
    contents:
      - index.qmd

format:
  seedcase-theme-html:
    theme:
      - brand

editor:
  markdown:
    wrap: 72
    canonical: true

execute:
  echo: false
